# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DifferenceOfSquares' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DifferenceOfSquares
  pod 'SwiftLint'
  target 'DifferenceOfSquaresTests' do
    # Pods for testing
  end

end

target 'DifferenceOfSquaresPackageDescription' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DifferenceOfSquaresPackageDescription

end
